<?php

/**
 * @file
 * Emailservice module functionality.
 */

/**
 * Implements hook_theme().
 */
function emailservice_theme($existing, $type, $theme, $path) {
  return [
    'subscription_manager' => [
      'template' => 'subscription-manager',
      'variables' => [
        'node' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function emailservice_preprocess_subscription_manager(&$variables) {
  if (!empty($variables['node'])) {
    $node = $variables['node'];

    $logo_array = $node->get('field_logo')->getValue();
    $file = \Drupal\file\Entity\File::load($logo_array[0]['target_id']);
    $logo = [
      '#theme' => 'image_style',
      '#style_name' => 'medium',
      '#uri' => $file->getFileUri(),
    ];

    $variables['logo'] = $logo;

    $intro = $node->get('field_intro_text')->getValue();
    $variables['intro'] = $intro[0]['value'];


    $fields = ['categories'=>'field_types_categories', 'types'=>'field_types_materials'];

    foreach ($fields as $name => $field) {
      $getfield = $node->get($field)->getValue();

      $options = [];
      foreach ($getfield as $key => $item) {
        $options[$item['machine_name']] = $item['label'];
      }

      $variables[$name] = $options;
      $a = 1;
    }
    $a = 1;

  }
}
